### ISSUE TITLE
Close inactive branches

### ISSUE THREAD

**Issue by alfredopizana** [CristopherCastaneda/devto#6]
I recommend to close the inactive and merged branches. You might want to only maintain the actives branches.

**Comment by CristopherCastaneda** [comment]
Como se que ya cerre la rama anterior?  Se cierra cuando creo otra rama? Enviado desde Correo para Windows De: alfredopizanaEnviado: martes, 5 de julio de 2022 08:03 p. m.Para: CristopherCastaneda/devtoCC: SubscribedAsunto: [CristopherCastaneda/devto] Close inactive branches (Issue #6) I recommend to close the inactive and merged branches. You might want to only maintain the actives branches.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by CristopherCastaneda** [comment]
Thank you for you feedback.
The inactive branches have been deleted

**Comment by alfredopizana** [comment]
Looks good, try to keep this as a good practice. Closing this ticket. Thanks.
